### ISSUE TITLE
[CT-2872] After upgrading dbt with version 1.5.3 getting ImportError: cannot import name 'RuntimeException' from 'dbt.exceptions' 

### ISSUE THREAD

**Issue by dmdeepakmittal1** [dbt-labs/dbt-core#8214]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

We are using dbt in python virtual env. and python version is 3.9. After upgradeing dbt to 1.5.3 version, we started getting below error.

ImportError: cannot import name 'RuntimeException' from 'dbt.exceptions' 

### Expected Behavior

dbt run command should run successfully.

### Steps To Reproduce

1.  setup virtual env
2. install python 3.9
3. install some older version of dbt
4. upgrade dbt with latest version 1.5.3
5. try to run any model using dbt run command.

### Relevant log output

```shell
in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

ImportError: cannot import name 'RuntimeException' from 'dbt.exceptions'
```

### Environment

```markdown
- OS: window
- Python:3.9
- dbt: 1.5.3
```

### Which database adapter are you using with dbt?

snowflake

**Comment by graciegoheen** [comment]
Hello - thanks for opening. Would you be able to check if you still get an error with a fresh install of `1.5.3`?
Additionally, what commands are you using to setup your virtual environment?
Thanks :)

**Comment by rjain** [comment]
I saw the same issue; however it disappeared after I upgraded dbt-snowflake (pip install --upgrade dbt-snowflake); it seems to be related to matching dependency versions

**Comment by graciegoheen** [comment]
Gotcha! Glad you were able to resolve the issue :)

**Comment by dmdeepakmittal1** [comment]
Hi,

Apologize for delayed response. But after setting up dbt locally issue was
resolved and we are able to use latest version without any issue. Thanks

Regards,
Deepak Mittal
