### ISSUE TITLE
[Regression] Error in freshness tests on Redshift external tables (DBT Cloud)

### ISSUE THREAD

**Issue by romj** [dbt-labs/dbt-core#9853]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

Freshness tests on external table do not run since I've upgraded from 1.6 to 1.7 on DBT cloud

The error is: 
``` 
Compilation Error in source customer_io_delivery_contents (models/staging/external_tables/external_tables_schema.yml)
 Got an invalid result from "get_relation_last_modified" macro: []
```

### Expected/Previous Behavior

Freshness tests work fine in 1.6

### Steps To Reproduce

1. You need a redshift cluster with an external table
2. Define a freshness test
3. run a freshness test

### Relevant log output

```shell
2024-04-04 09:34:38.389139 (Thread-1 (worker)): 09:34:38  Began running node source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents
2024-04-04 09:34:38.389736 (Thread-1 (worker)): 09:34:38  5 of 78 START freshness of external_raw_customer_io.customer_io_delivery_contents  [RUN]
2024-04-04 09:34:38.390512 (Thread-1 (worker)): 09:34:38  Re-using an available connection from the pool (formerly source.stonly_analytics.ads_google.ad_performance_reports, now source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents)
2024-04-04 09:34:38.390992 (Thread-1 (worker)): 09:34:38  Began compiling node source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents
2024-04-04 09:34:38.391546 (Thread-1 (worker)): 09:34:38  Timing info for source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents (compile): 09:34:38.391378 => 09:34:38.391382
2024-04-04 09:34:38.392045 (Thread-1 (worker)): 09:34:38  Began executing node source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents
2024-04-04 09:34:38.392986 (Thread-1 (worker)): 09:34:38  Using redshift connection "source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents"
2024-04-04 09:34:38.393486 (Thread-1 (worker)): 09:34:38  On source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents: BEGIN
2024-04-04 09:34:38.393976 (Thread-1 (worker)): 09:34:38  Opening a new connection, currently in state closed
2024-04-04 09:34:38.394551 (Thread-1 (worker)): 09:34:38  Redshift adapter: Establishing connection using ssl with `sslmode` set to 'prefer'.To connect without ssl, set `sslmode` to 'disable'.
2024-04-04 09:34:38.395052 (Thread-1 (worker)): 09:34:38  Redshift adapter: Connecting to redshift with username/password based auth...
2024-04-04 09:34:39.074450 (Thread-1 (worker)): 09:34:39  SQL status: SUCCESS in 1.0 seconds
2024-04-04 09:34:39.075564 (Thread-1 (worker)): 09:34:39  On source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents: COMMIT
2024-04-04 09:34:39.076465 (Thread-1 (worker)): 09:34:39  Using redshift connection "source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents"
2024-04-04 09:34:39.077219 (Thread-1 (worker)): 09:34:39  On source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents: COMMIT
2024-04-04 09:34:39.243804 (Thread-1 (worker)): 09:34:39  SQL status: SUCCESS in 0.0 seconds
2024-04-04 09:34:39.248409 (Thread-1 (worker)): 09:34:39  Using redshift connection "source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents"
2024-04-04 09:34:39.248978 (Thread-1 (worker)): 09:34:39  On source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents: BEGIN
2024-04-04 09:34:39.332892 (Thread-1 (worker)): 09:34:39  SQL status: SUCCESS in 0.0 seconds
2024-04-04 09:34:39.333517 (Thread-1 (worker)): 09:34:39  Using redshift connection "source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents"
2024-04-04 09:34:39.334014 (Thread-1 (worker)): 09:34:39  On source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents: /* {"app": "dbt", "dbt_version": "1.7.11", "profile_name": "user", "target_name": "prod", "node_id": "source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents"} */
select
            ns.nspname as "schema",
            c.relname as identifier,
            max(qd.start_time) as last_modified,
            getdate() as snapshotted_at
        from pg_class c
        join pg_namespace ns
            on ns.oid = c.relnamespace
        join sys_query_detail qd
            on qd.table_id = c.oid
        where qd.step_name = 'insert'
        and ((
                    upper(ns.nspname) = upper('external_raw_data')
                and upper(c.relname) = upper('ci_delivery_contents_customer_io')
                ))
        group by 1, 2, 4

2024-04-04 09:37:27.392694 (Thread-1 (worker)): 09:37:27  SQL status: SUCCESS in 168.0 seconds
2024-04-04 09:37:27.394203 (Thread-1 (worker)): 09:37:27  On source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents: ROLLBACK
2024-04-04 09:37:27.561375 (Thread-1 (worker)): 09:37:27  On source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents: Close
2024-04-04 09:37:27.562594 (Thread-1 (worker)): 09:37:27  Timing info for source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents (execute): 09:34:38.392422 => 09:37:27.562397
2024-04-04 09:37:27.564406 (Thread-1 (worker)): 09:37:27  Compilation Error in source customer_io_delivery_contents (models/staging/external_tables/external_tables_schema.yml)
  Got an invalid result from "get_relation_last_modified" macro: []
2024-04-04 09:37:27.565081 (Thread-1 (worker)): 09:37:27  5 of 78 ERROR freshness of external_raw_customer_io.customer_io_delivery_contents  [[31mERROR[0m in 169.17s]
2024-04-04 09:37:27.565769 (Thread-1 (worker)): 09:37:27  Finished running node source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents
```

### Environment

```markdown
- OS: DBT Cloud
- Python: DBT Cloud
- dbt (working version): 1.6
- dbt (regression version): 1.7
```

### Which database adapter are you using with dbt?

redshift
