### ISSUE TITLE
[Regression] Runtime Error when upgrading from 1.4.6 -> 1.5.0

### ISSUE THREAD

**Issue by mbkupfer** [dbt-labs/dbt-core#7592]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

dbt command returns the error:

```Runtime Error
  Compilation Error in model mmc_at_risk (models\path\to\model.sql)
    Object of type Undefined is not JSON serializable

    > in macro get_query_comment (macros\query_comment.sql)
    > called by model model (models\path\to\model.sql)
C:\Users\maxim.kupfer\Anaconda3\envs\py38\lib\multiprocessing\pool.py:265: ResourceWarning: unclosed running multiprocessing pool <multiprocessing.pool.ThreadPool state=RUN pool_size=4>
```

### Expected/Previous Behavior

Shouldn't be returning any error, such as when we run on the downgraded version.

### Steps To Reproduce

Sorry, I'm not too sure where even to begin on creating a way to reproduce this error outside of my environment. But glad to rollup the sleeves if someone wants to assist.

### Environment

```markdown
- OS: Windows 10
- Python:3.8.13
- dbt (working version): 1.4.6
- dbt (regression version): 1.5.0
```

### Which database adapter are you using with dbt?

snowflake

**Comment by jtcohen6** [comment]
@mbkupfer Thanks for opening! It looks like you have a custom implementation of the `get_query_comment` macro in your project. Would you be open to sharing it, so we can debug from there?

**Comment by mbkupfer** [comment]
@jtcohen6 I actually think this could be coming from a package we have.

I updated `dbt-snowflake-monitoring` to 2.0.0 and am now seeing a new error come up:

```
18:16:41  Encountered an error:
Compilation Error
  'dict object' has no attribute 'get_query_comment'
```

**Comment by dbeatty10** [comment]
It looks like `dbt-snowflake-monitoring` uses the [`get_query_comment`](https://github.com/get-select/dbt-snowflake-query-tags/blob/591ea48df3f85101a3503a72b572c62e34b4c441/macros/query_comment.sql) macro from `dbt-snowflake-query-tags`.

So it must be something in there that works in 1.4 but doesn't work in 1.5.

**Comment by mbkupfer** [comment]
@dbeatty10 that is correct. It appears the team is already aware and working on it in this issue: https://github.com/get-select/dbt-snowflake-monitoring/issues/102

**Comment by dbeatty10** [comment]
Sounds good @mbkupfer. I am going to close this in favor of https://github.com/get-select/dbt-snowflake-monitoring/issues/102.

We can re-open if this ends up being some kind of bug that we need to address in dbt-core.

**Comment by mbkupfer** [comment]
Yup, makes sense to me. Thanks @dbeatty10
