### PR TITLE
Fix generation of deprecations summary

### LINKED ISSUE #12146: [Bug] AttributeError: deprecation object has no attribute __name__ in Alpine Python 3.12.12
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When running any dbt command (e.g., dbt run) on Alpine Linux with Python 3.12.12, execution fails at the end with the following traceback:

AttributeError: 'PackageMaterializationOverrideDeprecation' object has no attribute '__name__'. Did you mean: '__ne__'?

It throws this same error for any deprecation warning not solved.

Apparently only happening on Alpine. Successfully ran the same commands on mac/amzn_linux distros.

### Expected Behavior

run with exit code 0

### Steps To Reproduce

run a model/test that hit any feature flagged for deprecation. 

`dbt build -s my_model_with_generic_tests`

The ones I could find where:

`MissingArgumentsPropertyInGenericTestDeprecation` 
`PackageMaterializationOverrideDeprecation`

### Relevant log output

```shell
12:39:54  Finished running 1 project hook, 2 data tests, 1 view model in 0 hours 0 minutes and 15.09 seconds (15.09s).
12:39:54  
12:39:54  Completed successfully
12:39:54  
12:39:54  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
Traceback (most recent call last):
  File "/usr/bin/dbt", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1462, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1383, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1850, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1246, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 814, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dbt/cli/main.py", line 149, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dbt/cli/requires.py", line 201, in wrapper
    show_deprecations_summary()
  File "/usr/lib/python3.12/site-packages/dbt/deprecations.py", line 269, in show_deprecations_summary
    event_name=deprecation_event.__name__,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dbt_common/events/base_types.py", line 88, in __getattr__
    return super().__getattribute__("pb_msg").__getattribute__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PackageMaterializationOverrideDeprecation' object has no attribute '__name__'. Did you mean: '__ne__'?
```

### Environment

```markdown
dbt-core | 1.10.13
dbt-databricks | 1.10.14
Python | 3.12.12
OS | Alpine Linux 3.22.2
Docker Image | bellsoft/liberica-openjdk-alpine:25.0.1-11-cds-x86_64
```

### Which database adapter are you using with dbt?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by asiunov**
Resolves #12146

### Problem

`__name__` field is not accessible on event objects.

```
  File ".venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 201, in wrapper
    show_deprecations_summary()
  File ".venv/lib/python3.12/site-packages/dbt/deprecations.py", line 270, in show_deprecations_summary
    event_name=deprecation_event.__name__,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/dbt_common/events/base_types.py", line 88, in __getattr__
    return super().__getattribute__("pb_msg").__getattribute__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MissingArgumentsPropertyInGenericTestDeprecation' object has no attribute '__name__'. Did you mean: '__ne__'?
```

It is likely a regression after https://github.com/dbt-labs/dbt-core/pull/11544/files#diff-3277eb602a187d7bfbcb01f646fa8a17697750aa5886869fddaea6c3026f03e1R208

### Solution

As it was supposed to be, call `__name__` on a class rather than an object.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me.
- [x] I have run this code in development, and it appears to resolve the stated issue.
- [x] This PR includes tests, or tests are not required or relevant for this PR.
- [x] This PR has no interface changes (e.g., macros, CLI, logs, JSON artifacts, config files, adapter interface, etc.) or this PR has already received feedback and approval from Product or DX.
- [x] This PR includes [type annotations](https://docs.python.org/3/library/typing.html) for new and modified functions.

### CODE REVIEW

**Comment by asiunov** [comment]
@QMalcolm @peterallenwebb could you please review? I think this is a regression after PR #11544

**Comment by QMalcolm** [comment]
@graciegoheen I'm gonna backport this to `1.10.latest` and `1.11.latest` once merged

**Comment by QMalcolm** [comment]
@asiunov we started requiring commits with verified signatures a few months ago. Unfortunately, we need to get the commits of this PR signed before we can proceed 😞 

If you don't have a GPG key already github has guides
* [Generating a new GPG key](https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key)
* [Adding a GPG key to your GitHub account](https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account)
* [Tell the git CLI about your GPG key](https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key)

And then here is a stackoverflow about how to sign all commits on a branch: https://stackoverflow.com/a/41883164

**Comment by asiunov** [comment]
@QMalcolm thank you for review and guidance on your processes. I've signed the commit.

**Comment by QMalcolm** [comment]
Backporting to 1.10.latest and 1.11.latest. This bug fix will go out in the next patch release of 1.10, and the next RC release of 1.11 🙂
