### ISSUE TITLE
[CT-1557] [Feature] dbt run flag to continue after compilation errors

### ISSUE THREAD

**Issue by kyle-kent** [dbt-labs/dbt-core#6324]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Sometimes when developing projects we can leave a model unfinished while working on others. These unfinished models create compilation errors due to dbt needing the fully developed DAG to execute. 

A flag like `--force` should be added to `dbt run --select <model>` to warn about these compilation errors but ultimately continue with the execution of the selected models. This offers flexibility to developers when they know an unrelated model (not in the same DAG) is broken.

A discussion of this feature: https://discourse.getdbt.com/t/compiling-models-will-break-runs-for-different-models/684

### Describe alternatives you've considered

The alternative is to fix the models with compilation errors or delete the broken code. It is much easier, and at times the only option, to delete and come back to the model later. This is less than ideal.

### Who will this benefit?

DBT users who quickly develop models or those who have many independent DAGs.

### Are you interested in contributing this feature?

Yes. Guidance on what scripts to start with.

### Anything else?

https://discourse.getdbt.com/t/compiling-models-will-break-runs-for-different-models/684

**Comment by dbeatty10** [comment]
Thanks for this idea @kyle-kent !

To make sure I'm following along with your scenario:
- are these unfinished models just in your local environment and in use by a single developer?
- or are the unfinished models being committed to your project's repository and/or being shared by multiple developers?

**Comment by kentkr** [comment]
@dbeatty10 thanks for the response! The first scenario is what I'm thinking. The second is possible but sounds like bad practice. 

This actually came up today during work. I moved a table from mart to intermediate and this raised a compilation error in tables and tests that I did not care about in that moment.

**Comment by dbeatty10** [comment]
@kentkr wow, very timely that it came up even today!

Drew did give a nice [high-level description](https://discourse.getdbt.com/t/compiling-models-will-break-runs-for-different-models/684/4) of such a feature in that discussion you referenced:
> I can definitely imagine adding a flag to dbt that would surface compilation errors as warnings. If a model with a compilation error is referenced by a model included in the dbt run, then this would result in a proper error. If the model is instead unrelated, then the compilation error could just be surfaced as a warning.

I don’t think this is something we’re going to prioritize in the near future, but wanted to give you a few different ideas for how to deal with this situation that we've all found ourselves in before:
1. Quick n' dirty trick 👈 
1. `git stash`
1. Commit in progress work, rebase or squash later

I'm going to assume that the instigating situation is that you were originally developing on one section of the code, but then needed to switch focus on some other section of the code before being able to finish the in-progress work.

### Quick n' dirty trick

There's two categories a node can be in:
1. leaf node (with no dependent nodes)
1. internal node (having at least one dependent node)

For the first category, here's a trick that I've used personally:
- rename the non-compiling model to be `my_model.sql.x` instead of `my_model.sql`

Since dbt only worries about certain file names (like `.yml`, `.sql`, and `.py`), it will ignore any files ending in `.x` like they don't even exist.

For the second category, you can do this variation:
- rename the non-compiling model to be `my_model.sql.x` instead of `my_model.sql`
- restore the original definition of `my_model.sql` that was compiling previously or just give it a dummy definition like `select 1`

### `git stash`

Assuming that your dbt project is stored in git and you have local uncommitted changes that are raising compile issues, `git stash` saves your local modifications away and reverts back to a clean working directory.

@jtemporal has a nice write up of how to use `git stash` [here](https://jtemporal.com/using-git-stash-and-git-stash-pop/).

### Commit in progress work, rebase or squash later

Of course we can always commit the in-progress work in a separate branch, then open a fresh branch for the divergent work.

The problem is that we might not love the resulting commit messages and that there were individual commits within the in-progress branch where the code didn't actually work. Let's assume that were able to come back later to the in-progress branch and finish it off and you want to clean things up before sharing this branch with others. 

One way to do this would be to perform an [interactive rebase to combine commits](https://about.gitlab.com/blog/2020/11/23/keep-git-history-clean-with-interactive-rebase/#combining-multiple-commits-into-one-using-interactive-rebase).

If you are using GitHub and your repository is configured to allow it, a separate option would be to squash the commits when merging the final pull request.

**Comment by kentkr** [comment]
@dbeatty10 thanks for the tips and I understand the lack of priority. I'd still like to contribute if you're willing to take a look at the PR.

I took a look at the code and am struggling to find where DBT creates a DAG and decides whether a dependency exists or not. Can you point me to where that occurs? Thanks!

**Comment by dbeatty10** [comment]
@kentkr There's at least one more option which I didn't think to mention earlier (because I hadn't yet used it myself):
- Adding the file(s) to [.dbtignore](https://docs.getdbt.com/reference/dbtignore)

### Using `.dbtignore`
Suppose I have a model named `my_model` that isn't working right now. Adding its path to the `.dbtignore` file will cause it to be ignored _before_ it is even compiled when running `dbt run --select <some other model>`:

`.dbtignore`
```
models/my_model.sql
```

### Review of options when there are compilation errors

We have quite the list of options to solve this problem when it arises:
1. add the file(s) to [.dbtignore](https://docs.getdbt.com/reference/dbtignore)
1. quick n' dirty trick (i.e., adding an `.x` to the end of the relevant file name)
1. commit in progress work, rebase or squash later
1. `git stash`
1. re-clone your project into a separate directory from the one with the broken models then run your project in the new directory
1. fix the compilation error(s)

All of these are possible today without any additional code. Among all of them, `.dbtignore` would probably be not much more cumbersome than adding a `--force` flag (especially if it's just one or two models that are causing issues). Once you know about it, it's pretty easy to do and also easy to undo.

### Upon further reflection
We want to be thoughtful of the time investment for the contributor (you!) as well as the code reviewers and make sure the "juice is worth the squeeze". In the particular case of a `--force` option, my gut says the implementation would be relatively complicated, take a fair amount of effort, and wouldn't yield a huge impact over pre-existing options. Even if we could magically snap our fingers and have this implemented already, it's _possible_ the additional code would make maintenance in the future more burdensome.

For those reasons, I'm going to close this issue.

I hope you know that we are always open to hearing your ideas and suggestions for how to improve our product! And we'd definitely welcome your contributions on other issues. For dbt-core specifically, we've got a nice little list of [`good_first_issue`](https://github.com/dbt-labs/dbt-core/issues?q=is%3Aopen+is%3Aissue+label%3Agood_first_issue)s. But you don't need to restrict yourself to just those -- we've got [lots of other repos](https://github.com/orgs/dbt-labs/repositories?q=&type=public&language=&sort=stargazers) to contribute to also! I'm looking forward to collaborating with you in the future.

**Comment by kentkr** [comment]
@dbeatty10 it did seem complicated lol. Thanks for the list of first issues to contribute to!
