### ISSUE TITLE
[Bug] Macro added twice during partial parsing 

### ISSUE THREAD

**Issue by crystalro0** [dbt-labs/dbt-core#4233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While in main/master branch, received compilation error: 

```
dbt found two macros named "<user_macro>" in the project "<user_project>"

To fix this error, rename or remove one of the following macros:
- /macros/foo/bar.sql
- /macros/foo/bar.sql
```

The error points to the same file twice, seems like the macro in question is duplicated within that file. Could not locate the duplicated entry in the file. The `*.yml` file was clear of duplicates as well.

### Expected Behavior

No compiler errors, possibly 3 warnings for this user.

### Steps To Reproduce

_Possible user steps:_
1. Create new file with 2 macros while in development environment and under new branch.
2. Add both macros to macros yml file.
3. Save commits and switch to main branch.
4. Compilation error is raised.

_Forced error steps:_ 
1. Create new file with 2 macros while in development environment and under new branch.
2. Add only one of the macros to macros yml file.
3. Compilation error is raised.

### Relevant log output

```shell
Error was seen during partial parsing compilation
```

### Environment

```markdown
- dbt: 0.21.0
```

### What database are you using dbt with?

redshift

For More Recent Instance:
### Relevant log output

```
08:46:39  Encountered an error:
Compilation Error
  dbt found two macros named "<macros_name>" in the project "<project_name>".
   To fix this error, rename or remove one of the following macros:
      - macros/foo/bar.sql
      - macros/foo/bar.sql
08:46:39  Command `dbt compile` failed at 11:46:39.886922 after 1.85 seconds
08:46:39  Flushing usage events
```

### Environment
- Python: 3.10.4
- dbt: 1.6.2

### Is this a new bug in dbt-core?
 I believe this is a new bug in dbt-core
 I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior
While run, compile or other command for partial parsing received Compilation Error:

```
dbt found two macros named "<user_macro>" in the project "<user_project>"

To fix this error, rename or remove one of the following macros:
- /macros/foo/bar.sql
- /macros/foo/bar.sql
```

### Expected Behavior
No error

### Steps To Reproduce
Create macros.sql file with 2 macros inside
Create macros.yml with documenation for this 2 macros
Run dbt compile
Change something in macros.yml
Run dbt compile again

### Relevant log output
```
08:46:39  Encountered an error:
Compilation Error
  dbt found two macros named "<macros_name>" in the project "<project_name>".
   To fix this error, rename or remove one of the following macros:
      - macros/foo/bar.sql
      - macros/foo/bar.sql
08:46:39  Command `dbt compile` failed at 11:46:39.886922 after 1.85 seconds
08:46:39  Flushing usage events
```

### Environment
- Python: 3.10.4
- dbt: 1.6.2

### Which database adapter are you using with dbt?
other (mention it in "Additional Context")

### Additional Context
dbt-adapter: dbt-athena: 1.6.1

**Comment by dbeatty10** [comment]
This was automatically closed as "stale" on Sep 17, 2022. Based on the report in https://github.com/dbt-labs/dbt-core/issues/8775, it was not resolved by https://github.com/dbt-labs/dbt-core/issues/4771.

**Comment by dbeatty10** [comment]
Re-opening.

Reprex as reported in [#8775](https://github.com/dbt-labs/dbt-core/issues/8775):

```
1. Create `macros/macros.sql` file with 2 macros inside
2. Create `macros/macros.yml` with documentation for these 2 macros
3. Run `dbt compile`
4. Change something in `macros/macros.yml`
5. Run `dbt compile` again
```

**Comment by dbeatty10** [comment]
### Implementation hints

https://github.com/dbt-labs/dbt-core/pull/4773 _might_ have some ideas for implementation.

**Comment by pcgarciar** [comment]
This issue still exists. I can reproduce it the same way OP did.

**Comment by dbeatty10** [comment]
Thank you for confirming @pcgarciar 

Does it resolve the error for you if you use the [--no-partial-parse](https://docs.getdbt.com/reference/global-configs/parsing) flag?

```shell
dbt compile --no-partial-parse
```

This the workaround that that we've been recommending in the meantime for this type of error message.

**Comment by jasmin-hemdani** [comment]
Hello @dbeatty10 ! I am also seeing this same issue after upgrading my dbt  version to 1.6.17 .
`There is a problem in your dbt project. Compilation failed: Compilation Error
  dbt found two macros named "materialization_materialized_view_default" in the
  project "dbt".
   To fix this error, rename or remove one of the following macros:
      - macros/materializations/models/materialized_view/materialized_view.sql
      - macros/materializations/models/materialized_view.sql`
      
     However I cannot locate these filepaths in my project at all. The recommended workaround 
   `  dbt compile --no-partial-parse` did not fix it.

**Comment by dbeatty10** [comment]
@jasmin-hemdani What is the output of `dbt --version`? That way, I can see all the dbt adapter plugins you have installed (and their versions).

Do you have any dbt packages installed via `dbt deps`? If so, could you share the contents of your relevant `packages.yml` / `dependencies.yml` file?

**Comment by cegarciar2305** [comment]
> Thank you for confirming @pcgarciar
> 
> Does it resolve the error for you if you use the [--no-partial-parse](https://docs.getdbt.com/reference/global-configs/parsing) flag?
> 
> ```shell
> dbt compile --no-partial-parse
> ```
> 
> This the workaround that that we've been recommending in the meantime for this type of error message.

Unfortunately that does not seem to fix it, but I found that deleting `manifest.json` does. However I'm scared that doing this might break other stuff (although that doesn't appear to be the case).

**Comment by sgalban-WTW** [comment]
> Hello @dbeatty10 ! I am also seeing this same issue after upgrading my dbt version to 1.6.17 . `There is a problem in your dbt project. Compilation failed: Compilation Error dbt found two macros named "materialization_materialized_view_default" in the project "dbt". To fix this error, rename or remove one of the following macros: - macros/materializations/models/materialized_view/materialized_view.sql - macros/materializations/models/materialized_view.sql` However I cannot locate these filepaths in my project at all. The recommended workaround ` dbt compile --no-partial-parse` did not fix it.

I have the same issue... any idea?

**Comment by dbeatty10** [comment]
@sgalban-WTW Does it resolve the error for you if you use the [--no-partial-parse](https://docs.getdbt.com/reference/global-configs/parsing) flag?

```shell
dbt compile --no-partial-parse
```

If not, does it resolve if you delete your `manifest.json` file?

There's a couple ways to do that:

1. `dbt clean`
2. `rm target/manifest.json` (or whatever the path to your manifest file is)

**Comment by sgalban-WTW** [comment]
HI! It still not working with this flag.

I have just deleted the dbt-adapters from my venv and it might be work

**Comment by dbeatty10** [comment]
@sgalban-WTW I wouldn't expect that deleting `dbt-adapters` from your virtual environment would affect this one way or the other.

Did you try deleting your [`target` directory](https://docs.getdbt.com/reference/global-configs/json-artifacts#target-path) and trying again? It is safe to delete your `target` directory because dbt will just recalculate what it needs from scratch.

**Comment by wusanny** [comment]
Hi Team, adding on here as the issue is still around. dbt Cloud customer reported seeing the error happen a few times, albeit randomly. The error seems to only pop up when editing the `macros.yml` file. 

The current workaround is to:
- Run `dbt parse --no-partial-parse`
- Or delete the `target/ folder` and then refresh Cloud IDE

I was able to reproduce it under certain conditions (similar to the comment [here](https://github.com/dbt-labs/dbt-core/issues/4233#issuecomment-1067021150)):
- Have multiple macros in `macros.sql`
- Edit/add macros with similar names in `macros.yml`

It is rather elusive though, sometimes reproducible a few times in a row with the same steps, other times, nothing happens. 

For me, the error always clears by deleting the `target/ folder`.

The issue has been around since 2021 and it is not always reproducible - is there anything that we can help with / provide in order to help the troubleshoot?

**Comment by dbeatty10** [comment]
Hey @wusanny !

My understanding is that deleting the `target` folder is a reliable way to clear the error.

I don't know of anything else that you can help with or provide.

Here's the way I've reproduced this error previously: https://github.com/dbt-labs/dbt-core/issues/4233#issuecomment-1749535081

And here's some potential implementation hints: https://github.com/dbt-labs/dbt-core/issues/4233#issuecomment-1749540702

**Comment by miyeung** [comment]
Hello,

I'm having the same problem when using VSCode dbt extension.

My whole `dbt_project.yml` appears with this error.

Anyone knows how to force the `no-partial-parse` flag when parsing the project by the extension? 

Thanks 🙏

**Comment by jeremyyeo** [comment]
Full repro:

```yaml
# dbt_project.yml
name: my_dbt_project
profile: all
version: "1.0.0"

# macros/sch.yml
macros:
  - name: foo
    description: Lorem.
  - name: bar
    description: Lorem.
```

```sql
-- macros/m.sql
{% macro foo() %}
    foo
{% endmacro %}

{% macro bar() %}
    bar
{% endmacro %}
```

^ Single file, 2 macros.

Do an initial parse:

```sh
$ dbt parse --no-partial-parse

22:29:57  Running with dbt=1.9.3
22:29:57  Registered adapter: snowflake=1.9.2
22:29:58  Performance info: /Users/jeremy/git/dbt-basic/target/perf_info.json
```

^ Note, a full parse will also happen if `target/` is empty and we didn't pass the `--no-partial-parse` flag but I'm just adding the `--no-partial-parse` flag for certainty :) 

Modify the yml file:

```yaml
# macros/sch.yml
macros:
  - name: foo
    description: Lorem.
  - name: bar
    description: Lorem ipsum.
```

Do a subsequent, partially parsed parse:

```sh
$ dbt parse

22:33:29  Running with dbt=1.9.3
22:33:29  Registered adapter: snowflake=1.9.2
22:33:29  Encountered an error:
Compilation Error
  dbt found two macros named "foo" in the project "my_dbt_project".
   To fix this error, rename or remove one of the following macros:
      - macros/m.sql
      - macros/m.sql
```
