### PR TITLE
Add support for Python 3.11

### LINKED ISSUE #6147: [CT-1411] [Feature] Support Python 3.11
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Support Python 3.11.x in dbt Core and adapters:
- https://github.com/dbt-labs/dbt-snowflake/issues/331
- https://github.com/dbt-labs/dbt-bigquery/issues/398
- https://github.com/dbt-labs/dbt-redshift/issues/225
- https://github.com/dbt-labs/dbt-spark/issues/524

### Describe alternatives you've considered

_No response_

### Who will this benefit?

Folks using the most recent release of Python

### Are you interested in contributing this feature?

Will mark as a "good first issue" and let someone else take a shot at this

### Last time
It looks like this work was split across multiple PRs last time, but it would be nice to have a single PR this time:
1. https://github.com/dbt-labs/dbt-core/pull/4866/files
1. https://github.com/dbt-labs/dbt-core/pull/5025/files

### How to implement

Add 3.11 (and 3.10 when it is missing) to these locations:
1. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/core/setup.py#L82-L84
1. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/tests/adapter/setup.py#L53-L54
1. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/plugins/postgres/setup.py#L84-L86
1. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/tox.ini#L5
1. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/tox.ini#L17
1. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/.github/workflows/main.yml#L74
2. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/.github/workflows/main.yml#L119
3. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/Dockerfile.test#L46-L51
4. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/CONTRIBUTING.md?plain=1#L59
5. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/CONTRIBUTING.md?plain=1#L163
1. Any other relevant file I may have missed in the two pull requests from last time (when we added Python 3.10)

### PR DESCRIPTION
**Pull request by joshuataylor**
resolves #6147

### Description
To support Python 3.11, various changes need to be made. Hopefully it won't be too much. I know that some BC Mashumaro changes will need to be made ([see here](https://github.com/Fatal1ty/mashumaro/releases/tag/v3.1)).

The other adapters will need to rely on this. I believe the Snowflake adapter (the only one I have experience with) might be a bit painful, due to Snowflake not planning on releasing wheels soon. Pyarrow 10.0.1 does support 3.11, so we'll see. :shrug: 

There are a few changes to be made with the dataclasses - see here: https://docs.python.org/3.11/whatsnew/3.11.html#dataclasses

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [ ] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by jtcohen6** [comment]
@joshuataylor Thanks for taking the initiative here!! We have every intent of including 3.11 compatibility for dbt-core v1.4 release (January).

It's possible that, due to varying dependencies, some adapters may not support py311 by then — that's ok, it's why we opened separate issues to track the upgrade for each.

It looks like there are some failing tests to sort out; I have a hunch that these are related to the changes to field defaults in dataclasses, which you flagged, and that they might be tricky to sort out. I think I was running into the same error (`AttributeError: '_MISSING_TYPE' object has no attribute 'replace_dict'`) when I made an attempt at this last month (https://github.com/dbt-labs/dbt-core/commit/48e6f96b3344f35dc2a3e4646898c89d63f8ae20). My hacky approach was to make some changes to how we initialize dataclasses that are themselves attributes of other dataclasses. While it worked enough to get a `dbt parse` off the ground, `mypy` wasn't too thrilled.

cc @leahwicz - Let's plan to devote some engineering capacity to this soon. We can decide whether it makes sense to build off Josh's excellent start here.

**Comment by jtcohen6** [comment]
@joshuataylor Thanks for taking the initiative here!! We have every intent of including 3.11 compatibility for dbt-core v1.4 release (January).

It's possible that, due to varying dependencies, some adapters may not support py311 by then — that's ok, it's why we opened separate issues to track the upgrade for each.

It looks like there are some failing tests to sort out; I have a hunch that these are related to the changes to field defaults in dataclasses, which you flagged, and that they might be tricky to sort out. I think I was running into the same error (`AttributeError: '_MISSING_TYPE' object has no attribute 'replace_dict'`) when I made an attempt at this last month (https://github.com/dbt-labs/dbt-core/commit/48e6f96b3344f35dc2a3e4646898c89d63f8ae20). My hacky approach was to make some changes to how we initialize dataclasses that are themselves attributes of other dataclasses. While it worked enough to get a `dbt parse` off the ground, `mypy` wasn't too thrilled.

cc @leahwicz - Let's plan to devote some engineering capacity to this soon. We can decide whether it makes sense to build off Josh's excellent start here.

**Comment by jtcohen6** [comment]
@joshuataylor Thanks for taking the initiative here!! We have every intent of including 3.11 compatibility for dbt-core v1.4 release (January).

It's possible that, due to varying dependencies, some adapters may not support py311 by then — that's ok, it's why we opened separate issues to track the upgrade for each.

It looks like there are some failing tests to sort out; I have a hunch that these are related to the changes to field defaults in dataclasses, which you flagged, and that they might be tricky to sort out. I think I was running into the same error (`AttributeError: '_MISSING_TYPE' object has no attribute 'replace_dict'`) when I made an attempt at this last month (https://github.com/dbt-labs/dbt-core/commit/48e6f96b3344f35dc2a3e4646898c89d63f8ae20). My hacky approach was to make some changes to how we initialize dataclasses that are themselves attributes of other dataclasses. While it worked enough to get a `dbt parse` off the ground, `mypy` wasn't too thrilled.

cc @leahwicz - Let's plan to devote some engineering capacity to this soon. We can decide whether it makes sense to build off Josh's excellent start here.

**Comment by joshuataylor** [comment]
Maybe for connectors which don't support Python 3.11 (Snowflake for example says "Q1 2023") yet we can document how to get that connector to work with 3.11.

I'm also happy to continue working on this and hammering through it, what sort of timeline do y'all have to look into this? Week(s)? Otherwise I'll continue looking into it this week. I believe the main blockers are the dataclass changes in 3.11.

I'd also be happy to get the dbt-snowflake stuff to work, I have tested Snowflake with 3.11 on both Linux/MacOS with Apple Silicon with native wheels and it works nicely.

**Comment by jtcohen6** [comment]
Timeline of next few weeks sounds right to me. We don't have this slated for our team's current sprint; we likely want to slot it in for the next one. If you're able to make progress in the meantime, amazing (+ much appreciated)!

**Comment by joshuataylor** [comment]
I'm shaving the hairiest yak with this one :-).

I've found a reference to https://github.com/python/mypy/issues/1362 , as I'm getting this issue with mashumaro and defaults:
```
ValueError: mutable default <enum 'NVEnum'> for field novalue is not allowed: use default_factory
```

I believe bumping mypy to the newest version might help, will keep digging and let you know. I'm playing with dbt-snowflake as well, and I believe it's just a matter of updating the `quote_policy` to the new 3.11 way of doing things and referencing the new library and that should be good, which is nice. So far it looks like pretty minimal changes are needed for libraries, with a few changes for core around dataclasses :tada: .

**Comment by joshuataylor** [comment]
@jtcohen6 I had to end up doing https://github.com/dbt-labs/dbt-core/pull/6321/commits/0172c4ed69075632352457b828f247d8844b442a#diff-1f46b05ee5e8edb06d10f6a5104795ccda0d1c2c458a203db4914d68115978b5 , or mashumaro would complain that the default NVEnum had changed.

**Comment by joshuataylor** [comment]
I've made a Snowflake PR here - https://github.com/dbt-labs/dbt-snowflake/pull/336

Once the connector is released, we can bump setup.py and in theory it'll work and we won't be blocked waiting for this PR, a release can just be cut with support for the new connector version :tada:

**Comment by jtcohen6** [comment]
@joshuataylor I'm going to close this in favor of https://github.com/dbt-labs/dbt-core/pull/6326, which looks just about good to go. I cherry-picked one of your commits, and included you in the changelog entry :)
