### ISSUE TITLE
[CT-1090] [Bug] dbt.type_timestamp() is not working using dbt 1.2.1

### ISSUE THREAD

**Issue by clausherther** [dbt-labs/dbt-core#5720]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Using dbt.type_timestamp() I get,
`dict object' has no attribute 'type_timestamp`
but it works using `type_timestamp()`. `dbt.<macro>()` works for others though.

### Expected Behavior

I expected `dbt.type_timestamp()` to work flawlessly :smi

### Steps To Reproduce

Using 1.2.1, try
```sql
select
    cast(my_column as {{ dbt.type_timestamp() }}) 
from
    my_model
```

### Relevant log output

```shell
'dict object' has no attribute 'type_timestamp'
```

### Environment

```markdown
- OS: Mac OS 12.51
- Python: 3.9
- dbt: 1.2.1
```

### Which database adapter are you using with dbt?

postgres, snowflake, bigquery

**Comment by jtcohen6** [comment]
In order to reproduce this:
- Custom generic test definition that references a `dbt.*` macro that was moved from `dbt_utils`
- A version of the `dbt_utils` package installed with backwards compatibility (= same macro in the `dbt_utils` namespace, dispatching into the `dbt` namespace)

**Why generic tests?** For parsing speed, dbt constructs slimmer rendering contexts when parsing generic tests. It attempts to include _just_ the macros that are called (depended on by) the generic test definition... and any macros those macros depend on, and so on. The `dict object' has no attribute 'type_timestamp'` error really means, for whatever reason, dbt isn't capturing that dependency, and including `type_timestamp` as a macro within the `dbt` namespace when parsing that generic test. (The `dbt` macro namespace is treating as a dictionary during macro resolution.)

If the package is installed, for whatever reason, dbt is resolving `{{ type_timestamp() }}` to point to `dbt_utils.type_timestamp` instead of `dbt.type_timestamp`. I'm not sure why—in general, only root project macros should get that kind of "global" priority; macros from packages should not—but in any case, `dbt_utils.type_timestamp` then redirects to `dbt.type_timestamp`, and all is well with the world.

In any case, it's possible to avoid this error by:
- referencing it just as `type_timestamp` in the generic test definition (or removing the test / the macro call entirely)
- uninstalling `dbt_utils` :)

In an ideal world, our macro dispatching/resolution order wouldn't yield this surprising outcome! I think the code involved here is pretty gnarly. IIRC it's around here:

https://github.com/dbt-labs/dbt-core/blob/5f59ff12549a035ce8be40bbb3b821db68a61870/core/dbt/context/macros.py#L128-L148

**Workaround:** Never use a `dbt.*` prefix ... for macros migrated from a package while also having a backwards-compatible of that package installed.

In a weird way, this issue (in its narrowest sense) will be fixed when `dbt_utils` removes that backwards compatibility. But we do risk running into this again in the future when we perform other package &rarr; core macro migrations.

**Comment by jtcohen6** [comment]
Taking another look here, since we might want to consider recommending `dbt.*` as the go-forward standard, instead of calling utility macros out of the global namespace, and this bug is a big scary thing standing in our way.

### Repro case

```
-- macros/some_test.sql
{% test some_test(model) %}
  select cast(current_timestamp as {{ dbt.type_timestamp() }})
  limit 0
{% endtest %}
```
```
-- models/some_model.sql
select 1 as id
```
```
# models/config.yml
version: 2
models:
  - name: my_model
    tests:
      - some_test
```
```
# packages.yml
packages:
  - package: dbt-labs/dbt_utils
    version: 0.9.2
# note that removing this, removes the bug!
```
```
$ dbt deps
$ dbt parse
...
dbt.exceptions.CompilationException: Compilation Error in test some_test_my_model_ (models/config.yml)
  'dict object' has no attribute 'type_timestamp'

  > in macro test_some_test (macros/custom_test.sql)
  > called by test some_test_my_model_ (models/config.yml)
```

### Big idea, restated

We build a special context for generic test parsing that contains _only_ the macros we think are necessary. That happens in these funky methods:

https://github.com/dbt-labs/dbt-core/blob/49ecd6a6a45c209857e23171f4c70d1c16a74304/core/dbt/context/providers.py#L1530-L1552

https://github.com/dbt-labs/dbt-core/blob/49ecd6a6a45c209857e23171f4c70d1c16a74304/core/dbt/context/macro_resolver.py#L130-L173

The problem: When `dbt_utils` is installed, dbt thinks that the generic test macro depends on `dbt_utils.type_timestamp`, instead of `dbt.type_timestamp`. So `dbt_utils.type_timestamp` shows up in the special test-parsing rendering context, whereas `dbt.type_timestamp` is missing, leading to the awkward error. (Yes, this error should also probably be better!)

This is the spot where we're saying that `some_test` depends on `dbt_utils.type_timestamp`, instead of `dbt.type_timestamp`:

https://github.com/dbt-labs/dbt-core/blob/49ecd6a6a45c209857e23171f4c70d1c16a74304/core/dbt/parser/manifest.py#L539

```
ipdb> possible_macro_calls
['dbt.type_timestamp']
ipdb> dep_macro_id
'macro.dbt_utils.type_timestamp'
```

**Why?** Because our macro resolution logic, which has special logic in case a specific package namespace has been specified, _does not use_ said logic if the specified package namespace is an "internal" namespace (`dbt`):

https://github.com/dbt-labs/dbt-core/blob/49ecd6a6a45c209857e23171f4c70d1c16a74304/core/dbt/context/macro_resolver.py#L110-L120

**Precise fix:** Add logic to `get_macro` that prefers macros defined in the `dbt` namespace, if a macro has been called as `dbt.some_macro`. This... makes sense to me!
**Blunt fix** (risks a performance hit): Just always include all macros from the `dbt` namespace in namespace for generic test parsing

The precise fix could _maybe_ be a breaking change for people who have been depending on funky/undocumented behavior around resolution order for global macros — namely, that my root project's `create_table_as()` will always "win" whenever `create_table_as()` _or_ `dbt.create_table_as()` is called. For the latter case, `dispatch` makes it possible to do this more clearly and explicitly, and I'm inclined to say it's the direction we should head in.
