### ISSUE TITLE
[CT-2783] [Feature] Compilation errors due to Jinja issues should say which file contains the issue

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#8023]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

As part of https://github.com/dbt-labs/internal-analytics/pull/1766, my CI run is getting errors because the metrics.calculate macro emits a deprecation warning that we are escalating to an error. The data team are away for 4 July weekend, so in the meantime I overrode `metrics.calculate` macro to remove the deprecation warning. 

I accidentally left the `{% if execute %}` tag but deleted the `{% endif %}` tag, so compilation failed. I got [this error in dbt Cloud](https://cloud.getdbt.com/deploy/1/projects/672/runs/167515978/): 

```
------------------------------------------------------------
  Invoke dbt Command
------------------------------------------------------------
dbt seed --select state:modified --exclude package:dbt_project_evaluator --full-refresh

03:16:44  Running with dbt=1.5.1
03:16:46  Unable to do partial parsing because saved manifest not found. Starting full parse.
03:16:47  Encountered an error:
Compilation Error
  Encountered unknown tag 'endmacro'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
    line 66
      {%- endmacro -%}
```

It doesn’t say what file is broken; I could work it out quickly because I had just changed a macro file, but we should make it easier. Something like this:

```
[...]
Compilation Error *in macro calculate (macros/temp_metrics_calculate_override.sql)*
  Encountered unknown tag 'endmacro'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
    line 66
      {%- endmacro -%}
```

### Who will this benefit?

People who use macros

**Comment by jtcohen6** [comment]
@joellabes Agree this would be a quality-of-life improvement!

I think this would require us to plumb through file names into methods like [`extract_toplevel_blocks`](https://github.com/dbt-labs/dbt-core/blob/7fbfd53c3e68d05577c4d73eb562e0c96ac83778/core/dbt/clients/jinja.py#L612) and [`catch_jinja`](https://github.com/dbt-labs/dbt-core/blob/7fbfd53c3e68d05577c4d73eb562e0c96ac83778/core/dbt/clients/jinja.py#L512). Not too tricky, but it will require tracking some small changes down a handful of our more intricate codepaths.

**Comment by gshank** [comment]
This might be a place where we can use the contextvar code that we're using for node_info (and now project_root). It's good for places where it's not realistic to pass information down a long codepath.

**Comment by graciegoheen** [comment]
The plan is to timebox work on this to 2.5 days
