### ISSUE TITLE
[CT-435] [Bug] Saving macro causes Partial Parsing 'Nonetype' error 

### ISSUE THREAD

**Issue by crystalro0** [dbt-labs/dbt-core#4971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When working in Cloud IDE v1.0.3, user is experiencing the following partial parse error whenever they save a change to one of their macros: : `'NoneType' object has no attribute 'read'`

They have 2 subfolders in the macros folder:
1st folder has 2 sql, 1 md (blank), 1 yml (blank) 
2nd folder has 1 sql, 1 md (filled), 1 yml (filled)

```
+ macros
| - subfolder1
|  | - macro1.sql
|  | - macro2.sql
|  | - macros.yml
|  | - macros.md
| - subfolder2
|  | - macro3.sql
|  | - macros.yml
|  | - macros.md 
```

As a troubleshooting step, I advised user to update the `macros/subfolder1/macros.yml` file to include a comment but still gets the same error.

### Expected Behavior

Changes to the macros should be saved without error. It should compile and return to Ready status.

### Steps To Reproduce

1. Log in to the dbt Cloud account
2. Access a dev environment on a project connected to Snowflake
3. Edit any macro files by adding a space or some other non-substantive change
4. Compilation error should appear.
5. Update blank yml file with comment and same error should appear.

### Environment

```markdown
- dbt: 1.0.3
```

### What database are you using dbt with?

snowflake

**Comment by emmyoop** [comment]
@crystalro0 and I chatted about this in slack.  Here's where we ended up:

I was not able to reproduce this behavior.  @crystalro0 will check with the customer now that they are in 1.0.5-rc1 in dev and see if they are still experiencing the issue.

For future reference, [this](https://github.com/emmyoop/basic-dbt/tree/triage/4971-parse-error) is the project I attempted to recreate the issue on.

**Comment by b-per** [comment]
I don't know if I should open a new issue or build upon this one but there are multiple reports in Slack of users getting this issue when they overwrite `generate_schema_name`. One of them is [this Slack thread](https://getdbt.slack.com/archives/C2JRRQDTL/p1651760710372859) (also pointing to another one). In the linked thread deleting `target` worked.

**Comment by emmyoop** [comment]
@b-per keeping the conversation in a single issue is always preferred so that all the context is together!

Transitioning this back to triage state to take a look in the next few days.
