### ISSUE TITLE
[Bug] Snapshot crashes with "invalid identifier" when adding new columns to source table with check_cols='all'

### ISSUE THREAD

**Issue by OmarAhmed-A** [dbt-labs/dbt-core#11735]
**Current Behavior**

When using dbt snapshots with the `check` strategy and `check_cols: all`, adding a new column to the source model causes the snapshot to fail with a SQL compilation error. The error message indicates that the new column identifier is invalid in the snapshotted data:

```
Database Error in snapshot testing_snap (snapshots\testing_snap.yml)
000904 (42000): SQL compilation error: error line 180 at position 12
invalid identifier 'SNAPSHOTTED_DATA.JOB_TITLE'
```

This issue was previously reported in #3146 and supposedly fixed in #4893, but it continues to occur in dbt 1.9.8.

**Expected Behavior**

When adding new columns to a source table, dbt snapshots should handle the schema evolution gracefully. According to the dbt documentation, snapshots should support "Creating new columns from the source query in the destination table." The snapshot should either:
1. Successfully add the new column and mark existing records as invalid (since their checksums would change)
2. Provide a clear migration path for handling schema changes

**Steps To Reproduce**

1. Create an initial model:
```sql
{{ config(materialized='table') }}

select
    1 as id,
    'Alice' as name,
    25 as age
union all
select
    2 as id,
    'Bob' as name,
    30 as age
union all
select
    3 as id,
    'Carol' as name,
    28 as age
```

2. Create a snapshot configuration:
```yaml
snapshots:
  - name: testing_snap
    relation: ref('testing_snap_pre')
    config:
      schema: snapshots
      unique_key: [ID]
      strategy: check 
      hard_deletes: new_record
      check_cols: all
```

3. Run the initial snapshot:
```bash
dbt snapshot --select testing_snap --target dev
```
✅ This succeeds

4. Update the model to include a new column:
```sql
{{ config(materialized='table') }}

select
    1 as id,
    'Alice' as name,
    25 as age,
    'Software Engineer' as job_title
union all
select
    2 as id,
    'Bob' as name,
    30 as age,
    'Data Analyst' as job_title
union all
select
    3 as id,
    'Carol' as name,
    28 as age,
    'Product Manager' as job_title
```

5. Run the snapshot again:
```bash
dbt snapshot --select testing_snap --target dev
```
❌ This fails with the invalid identifier error

**Relevant log output**

```shell
dbt snapshot --select testing_snap --target dev
01:52:35  Running with dbt=1.9.8
01:52:35  Registered adapter: snowflake=1.9.4
01:52:36  Unable to do partial parsing because of a version mismatch
01:52:38  Found 3 models, 1 snapshot, 4 data tests, 476 macros
01:52:38  
01:52:38  Concurrency: 1 threads (target='dev')
01:52:38  
01:52:43  1 of 1 START snapshot cmat_snapshots.testing_snap .............................. [RUN]
01:52:46  1 of 1 ERROR snapshotting cmat_snapshots.testing_snap .......................... [ERROR in 3.06s]
01:52:46  
01:52:46  Finished running 1 snapshot in 0 hours 0 minutes and 8.57 seconds (8.57s).
01:52:46  
01:52:46  Completed with 1 error, 0 partial successes, and 0 warnings:
01:52:46  
01:52:46    Database Error in snapshot testing_snap (snapshots\testing_snap.yml)
  000904 (42000): SQL compilation error: error line 180 at position 12
  invalid identifier 'SNAPSHOTTED_DATA.JOB_TITLE'
01:52:46  
01:52:46  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

**Environment**

- **OS**: Windows
- **Python**: 3.12.11 
- **dbt-core**: 1.9.8
- **dbt-snowflake**: 1.9.4

**Additional Context**

This appears to be a regression of issue #3146, which was supposedly resolved by PR #4893. However, the problem persists in the latest version of dbt-core (1.9.8). 

The original issue occurred with explicit `check_cols` lists, but this reproduction shows it also affects `check_cols: all`. The root cause seems to be that dbt generates SQL that references the new column in the existing snapshot table before that column has been added to the table schema.

Related issues:
- Original issue: #3146
- Supposed fix: #4893
- Related issue: #1797

**Comment by tonyg-chili** [comment]
I'm having a similar problem, but my snapshot uses strategy = 'timestamp' so I don't have a check_cols setting.  
Also, I'm using dbt cloud (dbt Cloud CLI - 0.40.3)

**Comment by BubbaTLC** [comment]
We are having the same issue with `dbt-core==1.8.9` and plugins `snowflake==1.8.4`

**Comment by OmarAhmed-A** [comment]
Have you found any workarounds? @BubbaTLC @tonyg-chili

**Comment by tonyg-chili** [comment]
@OmarAhmed-A no workarounds other than drop table and full refresh.
Pretty disappointing

**Comment by OmarAhmed-A** [comment]
> @OmarAhmed-A no workarounds other than drop table and full refresh.
> Pretty disappointing

That doesn't work, you lose the history. Thus the snapshot becomes useless..

**Comment by tonyg-chili** [comment]
@OmarAhmed-A 
Yep, fortunately for me I'm only dealing with a dev system right now.
For the production data (when the schema changes).  I'll need to do all types of
select into temptable with the new columns added and the old columns removed
then drop the real table
then select from temptable back into newtable

Its going to be a pain.

**Comment by tonyg-chili** [comment]
@OmarAhmed-A  or perhaps I'll have to dig into the dbt code and see if I can figure out a solution.  Not looking forward to that either.

**Comment by eckesru** [comment]
I am having the exact same issue. We are just starting to use dbt and it was really disappointing to see, that dbt can not handle this currently since it is so fundamental. I am glad that it is recocnized as a bug :)

**Comment by OmarAhmed-A** [comment]
I am surprised this issue has spent 14 days now un triaged and no one from the maintainers has commented.

**Comment by xrpza** [comment]
As a workaround, we manually evolved the schema by adding the new columns to our snapshot destination table and subsequently running the `snapshot. That seems to be working for now.

**Comment by OmarAhmed-A** [comment]
> As a workaround, we manually evolved the schema by adding the new columns to our snapshot destination table and subsequently running the `snapshot. That seems to be working for now.

This means the snapshot will have all the values with this new column will have their dates updated, are there any other side effects I haven't thought of?

Also, did you try automating the process via macros or similar?

**Comment by tonyg-chili** [comment]
Does anyone know when (which version) this problem started happening?

**Comment by xrpza** [comment]
> > As a workaround, we manually evolved the schema by adding the new columns to our snapshot destination table and subsequently running the `snapshot. That seems to be working for now.
> 
> This means the snapshot will have all the values with this new column will have their dates updated, are there any other side effects I haven't thought of?
> 
> Also, did you try automating the process via macros or similar?

- We did not work on automation because we only had this issue with a single snapshot table and a handful of new columns, so manual schema evolution was acceptable
- No historical data loss or mutation. Existing rows retained all data and had NULL values for new columns.
- No dates were updated on existing rows. Only new snapshot rows were created for rows with new column values that were previously null before our manual evolution.

**Comment by jeremyyeo** [comment]
I think it's probably `hard_deletes: new_record` - don't get the issue if the snapshot doesn't use that config - i.e.

```yaml
snapshots:
  - name: testing_snap
    relation: ref('foo')
    config:
      schema: snapshots
      unique_key: id
      strategy: check
      check_cols: all
```

**Comment by eckesru** [comment]
> I think it's probably `hard_deletes: new_record` - don't get the issue if the snapshot doesn't use that config - i.e.
> 
> snapshots:
>   - name: testing_snap
>     relation: ref('foo')
>     config:
>       schema: snapshots
>       unique_key: id
>       strategy: check
>       check_cols: all

I can confirm that the 'new_record' settings seems to be the issue.
Setting hard_deleted to 'ignore' successfully added the columns to the snapshot table (even tho it failed, because the dbt_is_deleted column was making issues)

**Comment by alex-indevets** [comment]
Same here, I have conclusive evidence that the issue is directly related to the new `hard_deletes: 'new_record'` feature. I'd like to help get this resolved for us ASAP -- what would be the appropriate path forward, @colin-rogers-dbt @drewbanin as this is still in triage?

**Comment by moreaupascal56** [comment]
Hi, encountered this issue as well and is a real blocker so +1

**Comment by colin-k-rogers** [comment]
closing as a fix has been merged, any further follow ups will be tracked in [dbt-labs/dbt-adapters#852](https://github.com/dbt-labs/dbt-adapters/issues/852)

**Comment by OmarAhmed-A** [comment]
> closing as a fix has been merged, any further follow ups will be tracked in [dbt-labs/dbt-adapters#852](https://github.com/dbt-labs/dbt-adapters/issues/852)

Hi I am unable to find the release where the fix has been added, how can I use it?

**Comment by graciegoheen** [comment]
@colin-rogers-dbt It looks like this was not properly resolved -> https://github.com/dbt-labs/dbt-core/issues/11766#issuecomment-3177592948

I re-opened https://github.com/dbt-labs/dbt-adapters/issues/852
