### ISSUE TITLE
[Bug] Macro dispatch crashes when a project name collides with a macro name ('MacroGenerator' object has no attribute 'get')

### ISSUE THREAD

**Issue by ash2shukla** [dbt-labs/dbt-core#15556]
### Is this a new bug?

- [x] I believe this is a new bug
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

`MacroNamespace.get_from_package` (in `core/dbt/context/macros.py`) raises an `AttributeError` during `adapter.dispatch` whenever a dbt project's name is identical to a macro name.

```
File ".../dbt/context/macros.py", line 40, in get_from_package
    return self[package_name].get(name)
AttributeError: 'MacroGenerator' object has no attribute 'get'
```

The regression was introduced by #15526 (Parsing Performance Improvements), which changed package resolution from:

```python
elif package_name == GLOBAL_PROJECT_NAME:
    return self.global_project_namespace.get(name)
elif package_name in self.packages:
    return self.packages[package_name].get(name)
else:
    raise PackageNotFoundForMacroError(package_name)
```

to:

```python
elif package_name in self:
    return self[package_name].get(name)
raise PackageNotFoundForMacroError(package_name)
```

`self[package_name]` now walks the entire namespace search order, which includes the flat `macro name -> Macro` maps. When a package name collides with a macro name, `__getitem__` returns a `MacroGenerator` (the macro) instead of a package sub-namespace, so the subsequent `.get(name)` fails.

This surfaced in dbt-adapters CI: the `get_catalog_for_single_relation` functional test names its project `get_catalog_for_single_relation`, which is also the name of a global macro. During setup (`create_schema` dispatch), resolution collides and the test errors out.

### Expected Behavior

A project name that happens to match a macro name should not break macro dispatch. `get_from_package` should resolve `package_name` only to package sub-namespaces (as it did before #15526), skipping any flat macro of the same name, and raise `PackageNotFoundForMacroError` (which `dispatch` catches) when no such package exists.

### Steps To Reproduce

1. Create a dbt project whose `name:` matches an existing macro name (e.g. `get_catalog_for_single_relation`).
2. Run any command that triggers `adapter.dispatch` under that project (e.g. schema creation / `dbt run`).
3. Dispatch fails with `AttributeError: 'MacroGenerator' object has no attribute 'get'`.

Alternatively, the dbt-adapters `TestGetCatalogForSingleRelation` functional test reproduces it.

### Relevant log output

```shell
.../dbt/context/providers.py:217: in dispatch
    macro = self._namespace.get_from_package(package_name, search_name)
.../dbt/context/macros.py:40: in get_from_package
    return self[package_name].get(name)
E   AttributeError: 'MacroGenerator' object has no attribute 'get'
```

### Environment

```markdown
- dbt-core: main (regression introduced in #15526)
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

Affects all adapters (observed in dbt-adapters Snowflake integration CI).
