### ISSUE TITLE
Column-based dimensions/entities missing expr when name differs from column name

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-core#12512]
## Description

When using the new v2 semantic layer YAML spec with column-level dimension or entity definitions, if the dimension/entity `name` differs from the column `name`, the `expr` field is not set in the semantic manifest. This causes MetricFlow to generate SQL using the dimension/entity name instead of the actual warehouse column name, resulting in `invalid identifier` errors during `dbt sl validate`.

## Example

```yaml
columns:
  - name: afe_number           # actual warehouse column
    dimension:
      type: categorical
      name: approval_afe_number  # user-friendly dimension name
```

This produces a `Dimension` with `name="approval_afe_number"` and `expr=None`. MetricFlow then queries `APPROVAL_AFE_NUMBER` instead of `AFE_NUMBER`, causing:

```
SQL compilation error: error line 63 at position 4
  invalid identifier 'APPROVAL_AFE_NUMBER'
```

## Expected behavior

When the dimension/entity name differs from the column name, `expr` should be set to the column name so MetricFlow queries the correct warehouse column. This is already how `fs` (dbt Fusion) handles it in `resolve_semantic_models.rs`.

## Root cause

In `core/dbt/parser/schema_yaml_readers.py`, both `_parse_v2_column_dimensions` and `_parse_v2_column_entities` omit the `expr` argument when constructing `Dimension` and `Entity` objects from column-level definitions.

Introduced in PR #12386.
