### ISSUE TITLE
dbt 0.21.0-b2: test aliases don't play well with anchored yaml

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#3815]
At https://github.com/dbt-labs/dbt/issues/3626#issuecomment-903687289, @jtcohen6 suggested:

>As it happens, thanks to the work in #3616, v0.21 will actually include support for the "long-term option" I described above: defining a custom `alias` under each specific test, which would enable you to avoid collisions with `--store-failures`. What do you think about that as a workable resolution here?

I gave it a go, and realised that hardcoded aliases collide with anchored YAML such as this: 
```yaml
  - name: hubspot_revenue__revenue_lines
    columns:
      - name: total_unweighted
        tests: &revenue_range_tests
          - not_null
          - accepted_range:
              alias: hubspot_revenue_test__total_unweighted_not_below_0
              where: "is_resub_adjustment is false"
              min_value: 0
              tags: 
                - hubspot_bad_revenue
          - accepted_range:
              alias: hubspot_revenue_test__total_unweighted_resub_adjustments_not_above_0
              where: "is_resub_adjustment is true"
              max_value: 0
              tags: 
                - hubspot_bad_revenue
      - name: resub_unweighted
        tests: *revenue_range_tests
      - name: resub_weighted
        tests: *revenue_range_tests
      - name: sale_unweighted
        tests: *revenue_range_tests
      - name: sale_weighted
        tests: *revenue_range_tests
```

Which gives the unsurprising error:
```
Compilation Error
  dbt found two resources with the database representation ""reporting"."dev_jlabes_dbt_test__audit"."hubspot_revenue_test__total_unweighted_not_below_0"".
  dbt cannot create two resources with identical database representations. To fix this,
  change the configuration of one of these resources:
  - test.educationperfect.accepted_range_hubspot_revenue__revenue_lines_total_unweighted__0.7a4a0581e3 (models\marts\revenue\hubspot_revenue\hubspot_revenue.yml)
  - test.educationperfect.accepted_range_hubspot_revenue__revenue_lines_resub_unweighted__0.9ac72c83e9 (models\marts\revenue\hubspot_revenue\hubspot_revenue.yml)
```

Knowing as I do that anchors are pretty inflexible, I don't think I have much choice other than to swap the templated code out for a bunch more copy-pasted stuff, right?
