### ISSUE TITLE
[Bug] FilterCallParameterSets renamed in upstream dbt_semantic_interfaces - affecting all dbt commands

### ISSUE THREAD

**Issue by mjsqu** [dbt-labs/dbt-core#11806]
### Is this a new bug in dbt-core?

- [x] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Running any dbt command:

```
dbt --version
```

Returns:
```
Traceback (most recent call last):
  File "/usr/local/bin/dbt", line 5, in <module>
    from dbt.cli.main import cli
  File "/usr/local/lib/python3.11/site-packages/dbt/cli/__init__.py", line 1, in <module>
    from .main import cli as dbt_cli  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/cli/main.py", line 13, in <module>
    from dbt.artifacts.schemas.run import RunExecutionResult
  File "/usr/local/lib/python3.11/site-packages/dbt/artifacts/schemas/run/__init__.py", line 2, in <module>
    from dbt.artifacts.schemas.run.v5.run import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/artifacts/schemas/run/v5/run.py", line 15, in <module>
    from dbt.artifacts.resources import CompiledResource
  File "/usr/local/lib/python3.11/site-packages/dbt/artifacts/resources/__init__.py", line 40, in <module>
    from dbt.artifacts.resources.v1.metric import (
  File "/usr/local/lib/python3.11/site-packages/dbt/artifacts/resources/v1/metric.py", line 8, in <module>
    from dbt.artifacts.resources.v1.semantic_layer_components import (
  File "/usr/local/lib/python3.11/site-packages/dbt/artifacts/resources/v1/semantic_layer_components.py", line 5, in <module>
    from dbt_semantic_interfaces.call_parameter_sets import FilterCallParameterSets
ImportError: cannot import name 'FilterCallParameterSets' from 'dbt_semantic_interfaces.call_parameter_sets' (/usr/local/lib/python3.11/site-packages/dbt_semantic_interfaces/call_parameter_sets.py)
```

I believe this has been caused by https://github.com/dbt-labs/dbt-semantic-interfaces/commit/ec362ab098a16a1a4b4011f3b436ea27a84f030c - I'll also raise an issue over in that repository which was recently updated

### Expected Behavior

`dbt deps` should run without error

### Steps To Reproduce

1. Pull https://github.com/dbt-labs/dbt-core/pkgs/container/dbt-postgres
2. In the container, run `pip install --upgrade dbt-core`
3. Run `dbt --version`

### Relevant log output

```shell

```

### Environment

```markdown
- OS: Linux
- Python: 3.11
- dbt: 1.10.3
```

### Which database adapter are you using with dbt?

snowflake

**Comment by mjsqu** [comment]
https://github.com/dbt-labs/dbt-semantic-interfaces have pulled release 0.8.6 from GitHub, but the package is still being installed from PyPi:
https://pypi.org/project/dbt-semantic-interfaces/#history

**Comment by oleg-agapov** [comment]
Can confirm this is happening for our project as well.

**Comment by aura-edwu** [comment]
How do i fix this issue? I also run into this error

**Comment by mjsqu** [comment]
I think this is now fixed - I have installed dbt-core from scratch and it is now picking up `dbt-semantic-interfaces-0.8.5`:

```
Successfully installed Jinja2-3.1.6 dbt-adapters-1.16.0 dbt-common-1.26.0 dbt-core-1.10.3 dbt-protos-1.0.337 dbt-semantic-interfaces-0.8.5

[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
bob@112f30e7b51c:/code/proj$ dbt --version
Core:
  - installed: 1.10.3
  - latest:    1.10.3 - Up to date!

Plugins:

```

**Comment by ryanjlind-agilitek** [comment]
is there a fix for this without updating to latest verison of dbt-core?

edit: pinning dbt-semantic-interfaces to 0.8.5 works

**Comment by aura-edwu** [comment]
yeah confirm it got fixed. the issue is gone

**Comment by dbeatty10** [comment]
Sorry the effect this snafu had on y'all.

I'm going to close this as resolved, but please reach out if you run into any further problems.
